project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('recipes.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from recipes.views import home, recipe, categories, search, category_search

app_name = 'recipes'

urlpatterns = [
    path('', home, name='home'),
    path('recipe/<str:slug>/', recipe, name='recipe'),
    path('categories/', categories, name='categories'),
    path('search/', search, name='search'),
    path(
        'categories/<str:category_name>',
        category_search,
        name='category_search'
    ),
]

recipes/models.py
from django.db import models
from utils.time_preparation_validation import time_validator
from django.utils.text import slugify
from utils.img_resizer import resize_image, if_image_changed, if_image_changed_category


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(
        max_length=36,
        unique=True,
        null=True,
        verbose_name='Nome',
    )

    category_image = models.ImageField(
        upload_to='assets/category_images/%Y/%m',
        blank=True,
        null=True,
        verbose_name='Imagem da categoria',
    )

    def save(self, *args, **kwargs):
        if self.category_image and if_image_changed_category(self):
            resized_image = resize_image(
                self.category_image,
                height=168,
                width=168,
            )
            self.category_image = resized_image
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


# Facilita a manutenção
class Difficulty(models.TextChoices):
    FACIL = 'Facil', 'Fácil'
    MEDIO = 'Medio', 'Médio'
    DIFICIL = 'Dificil', 'Difícil'


class Recipe(models.Model):
    class Meta:
        verbose_name = 'Recipe'
        verbose_name_plural = 'Recipes'

    recipe_title = models.CharField(
        max_length=70,
        unique=True,
        verbose_name='Título da receita',
    )

    slug = models.SlugField(unique=True, blank=True, null=True,)

    ingredients = models.TextField(
        max_length=1000,
        help_text='Separe os ingredientes por duas barras. Exemplo Cebola // Tomate // Alho',
        verbose_name='Ingredientes',
    )

    directions = models.TextField(
        max_length=2000,
        help_text='Separe os passos por duas barras. Exemplo Passo 1 // Passo 2 // Passo 3',
        verbose_name='Modo de Preparo',
    )

    preparation_time = models.CharField(
        max_length=9,
        help_text='Exemplos: 30min ou 1h 25min, etc',
        validators=[time_validator],
        null=True,
        verbose_name='Tempo de Preparo',
    )

    difficulty = models.CharField(
        max_length=7,
        choices=Difficulty.choices,
        verbose_name='Dificuldade',
    )

    tips = models.TextField(
        max_length=1000,
        null=True,
        blank=True,
        help_text='Campo não obrigatório',
        verbose_name='Dicas',
    )

    recipe_image = models.ImageField(
        upload_to='assets/recipe_images/%Y/%m',
        max_length=255,
        help_text='Envie imagens como o nome de no MÁXIMO 200 caracteres',
        null=False,
        blank=False,
        verbose_name='Imagem da Receita',
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Categoria',
    )

    servings = models.PositiveSmallIntegerField(
        blank=True,
        null=True,
        help_text='Campo não obrigatório',
        verbose_name='Porções',
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        null=True,
        verbose_name='Criado em:',
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        null=True,
        verbose_name='Atualizado em:',
    )

    show_recipe = models.BooleanField(
        default=True,
        verbose_name='Mostrar receita',
    )

    # A slug vai ser o titulo da receita, se for alterado a slug também será
    def save(self, *args, **kwargs):
        if not self.slug or self.slug != slugify(self.recipe_title):
            self.slug = slugify(self.recipe_title)
            # Garantir que o slug seja único
            original_slug = self.slug
            counter = 1
            while Recipe.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1

        if self.recipe_image and if_image_changed(self):
            resized_image = resize_image(
                self.recipe_image,
                height=400,
                width=840,
                quality=70,
                optimize=True,
            )
            self.recipe_image = resized_image

        super().save(*args, **kwargs)

    def __str__(self):
        return self.recipe_title

recipes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from recipes.models import Recipe, Category
from django.db.models import Q


def home(request,):
    recipes = Recipe.objects.all().filter(show_recipe=True).order_by('-id')[:8]
    categories = Category.objects.all().order_by('id')

    return render(
        request,
        'recipes/pages/home.html',
        {
            'recipes': recipes,
            'categories': categories,
            'page_title': 'Home'
        }
    )


def recipe(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug, show_recipe=True)
    categories = Category.objects.all().order_by('id')
    ingredients_list = recipe.ingredients.split('//')
    directions_list = recipe.directions.split('//')

    return render(
        request,
        'recipes/pages/recipe.html',
        {
            'recipe': recipe,
            'page_title': recipe.recipe_title,
            'categories': categories,
            'ingredients_list': ingredients_list,
            'directions_list': directions_list,
        }
    )


def categories(request):
    categories = Category.objects.all().order_by('id')

    return render(
        request,
        'recipes/pages/categories.html',
        {
            'page_title': 'Categorias',
            'categories': categories,
        }
    )


def search(request):
    search_value = request.GET.get('q', '').strip()
    categories = Category.objects.all().order_by('id')

    # O "Q" me permite fazer uma pesquisa, e o "|" é um ou
    recipes = Recipe.objects.filter(
        Q(recipe_title__icontains=search_value) |
        Q(difficulty__icontains=search_value) |
        Q(category__name__icontains=search_value)
    ).filter(show_recipe=True)

    if not search_value:
        return redirect('recipes:home')

    paginator = Paginator(recipes, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        'recipes/pages/home.html',
        {
            'recipes': page_obj,
            'page_title': search_value,
            'search_value': search_value,
            'categories': categories,
        }
    )


def category_search(request, category_name):
    category = get_object_or_404(Category, name=category_name)
    categories = Category.objects.all().order_by('id')
    category_recipes = Recipe.objects.filter(
        category=category,
        show_recipe=True
    )

    # Mudar a quantidade por página depois.
    paginator = Paginator(category_recipes, 12)
    page_number = request.GET.get('page')
    recipes = paginator.get_page(page_number)

    return render(
        request,
        'recipes/pages/home.html',
        {
            'recipes': recipes,
            'page_title': category,
            'categories': categories,
        }
    )

recipes/templates/recipes/partials/footer.html
<footer>
  <div class="footer-container">
    
    <div class="footer-copyright">
      <h3>{{ site_config.domain }}</h3>
      <p>Copyright® {{ site_config.site_name }} {% now "Y"%} - Todos os direitos reservados.</p>
    </div>
    
    <div class="footer-resources">
      <h3>Receitas por tag</h1>
      {% for category in categories|slice:2 %}
        <a href="{% url "recipes:category_search" category.name %}">{{ category }}</a>
      {% endfor %}
      <a href="{% url "recipes:categories" %}">Categorias</a>
    </div>

      <div class="footer-socials">
        <h3>Nos acompanhe nas redes sociais</h3>
        <a href="{{ site_config.youtube }}" target="_blank"><i class="fa-brands fa-youtube"></i></a>
        <a href="{{ site_config.tiktok }}" target="_blank"><i class="fa-brands fa-tiktok"></i></a>
        <a href="{{ site_config.instagram }}" target="_blank"><i class="fa-brands fa-instagram"></i></a>
        <a href="{{ site.config.twitter }}" target="_blank"><i class="fa-brands fa-twitter"></i></i></a>
      </div>
      
      <div class="footer-logo">
        <img class="logo-footer" src="{{ site_config.footer_logo.url }}" alt="Logo da empresa">
        <div class="contact-container">
          <i class="fa-regular fa-envelope"></i>
          <p>{{ site_config.email }}</p>
        </div>
      </div>

  </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="{% static "recipes/css/remedy.css" %}">
<link rel="stylesheet" href="{% static "recipes/css/style.css" %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

<!-- FONTES -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap">

{% if site_config.favicon %}
  <link rel="shortcut icon" href="{{ site_config.favicon.url }}" type="image/x-icon">
{% endif %}

<title>{{ page_title }} - {{ site_config.site_name }}</title>

recipes/templates/recipes/partials/menu.html
<div class="header-container">
  <header class="menu main-content">
    <div class="logo-menu">
      <a href="{% url "recipes:home" %}"><img src="{{ site_config.footer_logo.url }}" alt="Logo da empresa"></a>
    </div>

    <nav class="nav-menu">
    {% for category in categories|slice:2 %}
      <a href="{% url "recipes:category_search" category.name %}">{{ category }}</a>
    {% endfor %}
     <a href="{% url "recipes:categories" %}">Categorias</a>
    </nav>

    <form class="search-container" method="GET" action="{% url "recipes:search" %}">
      <label type="hidden"  for="search" class="hidden">Procurar Receita</label>
      <input 
        class="search-input"
        id="search"
        type="search"
        name="q"
        placeholder="Procurar Receita"
        alt="Input de busca" 
        value="{{ search_value }}"
      >
      <button class="search-btn" type="submit"> 
        <i class="fa-solid fa-magnifying-glass"></i>
      </button>
    </form>
  </header>
</div>

recipes/templates/recipes/partials/pagination.html
{% if recipes and recipes.has_other_pages %}
<div class="pagination main-content">
  <span class="step-links">
    {% if recipes.has_previous %}
    <a href="?page=1&q={{ request.GET.q.strip }}">
      <i class="fa-solid fa-backward"></i>
    </a>
    <a href="?page={{ recipes.previous_page_number }}&q={{ request.GET.q.strip }}">
      <span class="previous">Anterior</span>
    </a>
    {% endif %}

    <!-- Números das páginas com intervalo -->
    <span class="page-numbers">
      {% for num in recipes.paginator.page_range %}
      {% if num == recipes.number %}
      <span class="current">{{ num }}</span> <!-- Página atual -->
      {% elif num > recipes.number|add:-5 and num < recipes.number|add:2 %} <a
        href="?page={{ num }}&q={{ request.GET.q.strip }}">{{ num }}</a> <!-- Páginas próximas -->
        {% elif num == 1 or num == recipes.paginator.num_pages %}
        <a href="?page={{ num }}&q={{ request.GET.q.strip }}">{{ num }}</a> <!-- Primeira e Última página -->
        {% elif num == recipes.number|add:-6 or num == recipes.number|add:6 %}
        <span>...</span>
        {% endif %}
        {% endfor %}
    </span>

    {% if recipes.has_next %}
    <a href="?page={{ recipes.next_page_number }}&q={{ request.GET.q.strip }}">
      <span class="next">Proxima</span>
    </a>
    <a href="?page={{ recipes.paginator.num_pages }}&q={{ request.GET.q.strip }}">
      <i class="fa-solid fa-forward"></i>
    </a>
    {% endif %}
  </span>
</div>
{% endif %}