project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('recipes.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from recipes.views import home, recipe, categories, search, category_search

app_name = 'recipes'

urlpatterns = [
    path('', home, name='home'),
    path('recipe/<str:slug>/', recipe, name='recipe'),
    path('categories/', categories, name='categories'),
    path('search/', search, name='search'),
    path(
        'categories/<str:category_name>',
        category_search,
        name='category_search'
    ),
]

recipes/models.py
from django.db import models
from utils.time_preparation_validation import time_validator
from django.utils.text import slugify
from utils.img_resizer import resize_image, if_image_changed, if_image_changed_category


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(
        max_length=36,
        unique=True,
        null=True,
        verbose_name='Nome',
    )

    category_image = models.ImageField(
        upload_to='assets/category_images/%Y/%m',
        blank=True,
        null=True,
        verbose_name='Imagem da categoria',
    )

    def save(self, *args, **kwargs):
        if self.category_image and if_image_changed_category(self):
            resized_image = resize_image(
                self.category_image,
                height=168,
                width=168,
            )
            self.category_image = resized_image
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


# Facilita a manutenção
class Difficulty(models.TextChoices):
    FACIL = 'Facil', 'Fácil'
    MEDIO = 'Medio', 'Médio'
    DIFICIL = 'Dificil', 'Difícil'


class Recipe(models.Model):
    class Meta:
        verbose_name = 'Recipe'
        verbose_name_plural = 'Recipes'

    recipe_title = models.CharField(
        max_length=70,
        unique=True,
        verbose_name='Título da receita',
    )

    slug = models.SlugField(unique=True, blank=True, null=True,)

    ingredients = models.TextField(
        max_length=1000,
        help_text='Separe os ingredientes por duas barras. Exemplo Cebola // Tomate // Alho',
        verbose_name='Ingredientes',
    )

    directions = models.TextField(
        max_length=2000,
        help_text='Separe os passos por duas barras. Exemplo Passo 1 // Passo 2 // Passo 3',
        verbose_name='Modo de Preparo',
    )

    preparation_time = models.CharField(
        max_length=9,
        help_text='Exemplos: 30min ou 1h 25min, etc',
        validators=[time_validator],
        null=True,
        verbose_name='Tempo de Preparo',
    )

    difficulty = models.CharField(
        max_length=7,
        choices=Difficulty.choices,
        verbose_name='Dificuldade',
    )

    tips = models.TextField(
        max_length=1000,
        null=True,
        blank=True,
        help_text='Campo não obrigatório',
        verbose_name='Dicas',
    )

    recipe_image = models.ImageField(
        upload_to='assets/recipe_images/%Y/%m',
        max_length=255,
        help_text='Envie imagens como o nome de no MÁXIMO 200 caracteres',
        null=False,
        blank=False,
        verbose_name='Imagem da Receita',
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Categoria',
    )

    servings = models.PositiveSmallIntegerField(
        blank=True,
        null=True,
        help_text='Campo não obrigatório',
        verbose_name='Porções',
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        null=True,
        verbose_name='Criado em:',
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        null=True,
        verbose_name='Atualizado em:',
    )

    show_recipe = models.BooleanField(
        default=True,
        verbose_name='Mostrar receita',
    )

    # A slug vai ser o titulo da receita, se for alterado a slug também será
    def save(self, *args, **kwargs):
        if not self.slug or self.slug != slugify(self.recipe_title):
            self.slug = slugify(self.recipe_title)
            # Garantir que o slug seja único
            original_slug = self.slug
            counter = 1
            while Recipe.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1

        if self.recipe_image and if_image_changed(self):
            resized_image = resize_image(
                self.recipe_image,
                height=400,
                width=840,
                quality=70,
                optimize=True,
            )
            self.recipe_image = resized_image

        super().save(*args, **kwargs)

    def __str__(self):
        return self.recipe_title

recipes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from recipes.models import Recipe, Category
from django.db.models import Q


def home(request,):
    recipes = Recipe.objects.all().filter(show_recipe=True).order_by('-id')[:8]
    categories = Category.objects.all().order_by('id')

    return render(
        request,
        'recipes/pages/home.html',
        {
            'recipes': recipes,
            'categories': categories,
            'page_title': 'Home'
        }
    )


def recipe(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug, show_recipe=True)
    categories = Category.objects.all().order_by('id')
    ingredients_list = recipe.ingredients.split('//')
    directions_list = recipe.directions.split('//')

    return render(
        request,
        'recipes/pages/recipe.html',
        {
            'recipe': recipe,
            'page_title': recipe.recipe_title,
            'categories': categories,
            'ingredients_list': ingredients_list,
            'directions_list': directions_list,
        }
    )


def categories(request):
    categories = Category.objects.all().order_by('id')

    return render(
        request,
        'recipes/pages/categories.html',
        {
            'page_title': 'Categorias',
            'categories': categories,
        }
    )


def search(request):
    search_value = request.GET.get('q', '').strip()
    categories = Category.objects.all().order_by('id')

    # O "Q" me permite fazer uma pesquisa, e o "|" é um ou
    recipes = Recipe.objects.filter(
        Q(recipe_title__icontains=search_value) |
        Q(difficulty__icontains=search_value) |
        Q(category__name__icontains=search_value)
    ).filter(show_recipe=True)

    if not search_value:
        return redirect('recipes:home')

    paginator = Paginator(recipes, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        'recipes/pages/home.html',
        {
            'recipes': page_obj,
            'page_title': search_value,
            'search_value': search_value,
            'categories': categories,
        }
    )


def category_search(request, category_name):
    category = get_object_or_404(Category, name=category_name)
    categories = Category.objects.all().order_by('id')
    category_recipes = Recipe.objects.filter(
        category=category,
        show_recipe=True
    )

    # Mudar a quantidade por página depois.
    paginator = Paginator(category_recipes, 12)
    page_number = request.GET.get('page')
    recipes = paginator.get_page(page_number)

    return render(
        request,
        'recipes/pages/home.html',
        {
            'recipes': recipes,
            'page_title': category,
            'categories': categories,
        }
    )

recipes/templates/recipes/pages/categories.html
{% extends "base.html" %}

{% block content %}
  <div class="text-with-line main-content">
    <div class="text-line-container">
      <hr>
      <h2>CATEGORIAS</h2>
      <hr>
    </div>
      <p>ESCOLHA A CATEGORIA QUE DESEJA EXPLORAR</p>
    </div>

  <div class="category-card-grid main-content">
    {% for category in categories %}
      <a href="{% url "recipes:category_search" category.name %}">
        <div class="category-card">

          {% if category.category_image %} 
            <div class="category-card-image"> <img src="{{ category.category_image.url }}"/> </div>
            {% else %}
            <div class="category-card-image"> <img src="https://placehold.co/168"/> </div>
          {% endif %}

          <div class="category-card-title"> <p>{{ category.name }}</p> </div>
        </div>
      </a>
    {% endfor %}
  </div>
 
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends "base.html" %}

{% block content %}

{% if recipes %}
    <div class="text-with-line main-content">
      <div class="text-line-container">
        <hr>
        <h2>ESCOLHA SUA RECEITA</h2>
        <hr>
      </div>
      <p>ULTIMAS RECEITAS</p>
    </div>

    <div class="card-grid main-content">
    {% for recipe in recipes %}
      <div class="card-2">
        
        <a href="{% url "recipes:recipe" recipe.slug %}"><img src="{{ recipe.recipe_image.url }}" alt="Imagem de {{ recipe.recipe_title }}"></a>
        <h3>{{ recipe.category }} / {{ recipe.created_at|date:"d M Y" }}</h3>

        <h1>{{ recipe.recipe_title }}</h1>

        <div class="preparation-time">
          <i class="fa-solid fa-clock"></i>
          <h2>{{ recipe.preparation_time }}</h2>

          {% comment %}
          .get_FOO_display() é um método do django para campos com choices,
          ele retorna o valor legível da tupla, e não o que é armazena no banco de dados
          {% endcomment %}
          {% if recipe.difficulty == 'Facil' %}
            <i class="fa-regular fa-star"></i>
            <h2>{{ recipe.get_difficulty_display }}</h2>

          {% elif recipe.difficulty == 'Medio' %}
            <i class="fa-solid fa-star-half-stroke"></i>
            <h2>{{ recipe.get_difficulty_display }}</h2>

          {% else %}
            <i class="fa-solid fa-star"></i>
            <h2>{{ recipe.get_difficulty_display }}</h2>
          {% endif %}
        </div>

        <div class="read-more">
          <a class="read-more-btn" href="{% url 'recipes:recipe' recipe.slug %}">Ver Receita</a>
          <i class="fa-solid fa-arrow-right"></i>
        </div>
      </div>
      {% endfor %}
    </div>

    {% else %}
    <div class="text-with-line main-content">
      <div class="text-line-container">
        <hr>
        <h2>NADA ENCONTRADO</h2>
        <hr>
      </div>
      <p>Daidai</p>
    </div>
 
    </div>  

    <div class="main-content not-found">
      <h1>Desculpe, não conseguimos encontrar o que você procura. Tente novamente!</h1>
      <br>
      <h1>Sugestões</h1>
      <p>Verifique a ortografia</p>
      <p>Você pode pesquisar pelo título da receita, categorias e dificuldade.</p>
      <br>
      <a href="{% url "recipes:home" %}">Voltar a pagina inicial</a>
    </div>
{% endif %}
{% endblock content %}

recipes/templates/recipes/pages/recipe.html
{% extends "base.html" %}

{% block content %}

<div class="recipe-page-container">
  <article class="recipe-page-content">

    <div class="recipe-page-title-container">
      <h1 class="">{{ recipe.recipe_title }}</h1>
    </div>

    <div class="recipe-page-img">
      <img src="{{ recipe.recipe_image.url }}" alt="Foto de {{ recipe.recipe_title }}">
    </div>

    <div class="recipe-details">
      <div class="time">
        <i class="fa-solid fa-clock"></i>
        <h2>{{ recipe.preparation_time }}</h2>
      </div>
      <div class="difficulty">
        {% if recipe.difficulty == 'Facil' %}
        <i class="fa-regular fa-star"></i>
        <h2>{{ recipe.get_difficulty_display }}</h2>

        {% elif recipe.difficulty == 'Medio' %}
        <i class="fa-solid fa-star-half-stroke"></i>
        <h2>{{ recipe.get_difficulty_display }}</h2>

        {% else %}
        <i class="fa-solid fa-star"></i>
        <h2>{{ recipe.get_difficulty_display }}</h2>
        {% endif %}
      </div>

      {% if recipe.servings > 0 %}
        <div class="servings">
          {% if recipe.servings == 1 %}
            <h2>{{ recipe.servings }} Porção</h2>
          {% else %}
            <h2>{{ recipe.servings }} Porções</h2>
          {% endif %}
        </div>
      {% endif %}

    </div>

    <div class="text-with-line">
      <div class="text-line-container">
        <hr>
        <h2>Ingredientes</h2>
        <hr>
      </div>
      {% if recipe.servings > 0 and recipe.servings == 1 %}
        <p>{{ recipe.servings }} Porção</p>
        {% else %}
        <p>{{ recipe.servings }} Porções</p>
      {% endif %}
    </div>

    <div class="ingredients">
      <ul>
        {% for ingredient in ingredients_list %}
        <li>{{ ingredient }}</li>
        {% endfor %}
      </ul>
    </div>

    <div class="text-with-line">
      <div class="text-line-container">
        <hr>
        <h2>Modo de Preparo</h2>
        <hr>
      </div>
      <p>{{ recipe.preparation_time }}</p>
    </div>

    <div class="recipe-page-directions">
      <div class="direction">
        <ol>
          {% for direction in directions_list %}
          <li>{{ direction }}</li>
          {% endfor %}
        </ol>
      </div>
    </div>

    {% if recipe.tips %}
    <div class="text-with-line">
      <div class="text-line-container">
        <hr>
        <h2>Dicas</h2>
        <hr>
      </div>
    </div>
    <div class="recipe-page-tips">
      {% comment %} linebreaks adiciona as quebras de linha do textfield no template{% endcomment %}
      <p>{{ recipe.tips|linebreaks }}</p>
    </div>
    {% endif %}

  </article>

  <aside class="recipe-page-aside">
    <h1>Você pode gostar</h1>
    <p>Em breve </p>
  </aside>

</div>
{% endblock content %}